### ISSUE TITLE
Add "cloud service" tag

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/ecosystem#776]
Many ecosystem projects are based around cloud services. The main example is a provider package through which users submit jobs to QPUs. We should add a "cloud service" label for projects with non-free features like these to set user expectations.

### Todo
- [ ] Add the new tag
- [ ] Review existing projects manually and add the tag where appropriate
- [ ] Update the submission form with the new tag
